### ISSUE TITLE
Can't declare arrays on OS X

### ISSUE THREAD

**Issue by pvitaly** [tblyler/hoarder#4]
lines 246 and 248 have 'declare -A'

I had to change that to lower case a: 'declare -a' to work on my mac. I wanted to push the code to a new branch and create a PR, but of course I didn't have permissions :)

**Comment by JohnMaguire** [comment]
Made a PR! :+1: 

On Github, you can "Fork" by clicking the button on the top right, which'll create a hoarder fork on your profile. Push a branch there, and you'll see a pull request button. :)

**Comment by tblyler** [comment]
The issue here is that it appears you are running bash less than version 4. The capitalized A is required for [associative arrays](https://www.gnu.org/software/bash/manual/html_node/Arrays.html).
